# Pythagorean Expectation Via Weibull Distribution

The goal of this notebook is to build a model to predict the winner of a baseball game using the data gathered as a season goes forward. The main idea of rather using the Pythagorean Expectation is to use the idea of Steven J. Miller's paper "A Derivation of the Pythagorean Won-Lose Formula in Baseball" (see https://arxiv.org/pdf/math/0509698.pdf). However, rather using the actual Pythagorean Expectation as our measure of whether or not a team will win, we will use the empirical observation that the Pythagorean Expectation is a good approximation for the actual win percentage in baseball. Furthermore, as the paper shows the Pythagorean Expectation gives the precise win percentage when we make the assumption that the runs scored and runs allowed follow Weibull distributions with given parameters. Thus, the idea of the model will be to use this observation, so for any particular game between two games look at how the teams previously did throughout the season to determine what the appropriate parameters for their Weibull distribution will be for that particular game. Then we shall simulate several games for how many runs will be scored by each team using these distributions to predict who will win the game.

Note: this notebook is meant more of a proof of concept, so we shall only focus on the data from the 2010 season.

In [1]:
##Import of packages that we will use 
import pandas as pd
import numpy as np
import math

Note: the data we are reading in will be an adjusted version of Joe's game data, but we have removed the variables which we do not use (i.e. win percentage, pythagorean expectation, etc.), we have also added additional columns that we will be using to get the parameters for the Weibull distribution. Primarily, we have added a cumulative runs scored and allowed columns which consist of the cumulative runs scored and allowed before that particular game (thus for the first game each team will have 0 to initialize). We have used these cumulative runs/scored and allowed to calculate the Weibull distribution parameters at that point in the season.

Remark: The three parameter Weibull distribution has pdf 
$$
f(x;\alpha,\beta,\gamma)=\begin{cases}
\frac{\gamma}{\alpha}\left(\frac{x-\beta}{\alpha}\right)^{\gamma-1}e^{-\left(\frac{x-\beta}{\alpha}\right)^\gamma} & x\geq \beta\\
0 & \text{else}
\end{cases}
$$
Per the paper, we note that $\gamma$ corresponds to the exponent appearing in the Pythagorean Expectation formula, for simplicity of the model, we shall make the assumption in what follows is that $\gamma=1.82$ as a constant which we shall not change. Furthermore, per the commment the variable $\beta$ is just a translation which has no affect if we assume that it is constant in all cases (and was included, so that the ideas may be extrapolated to other sports with higher scoring games). For baseball Miller takes $\beta=-.5$, so that the bins are centered at integers. Thus, we shall take these variables to be constant throughout. Now per equation (2.8), we have a formula for the parameter $\alpha$ for each team given by 
$$
\alpha_{RS}(n+1)=\frac{RS(n)-\beta}{\Gamma(1+\gamma^{-1})}
$$
and
$$
\alpha_{RA}=\frac{RA-\beta}{\Gamma(1+\gamma^{-1})}
$$
Thus, if we use the previous RS and RA for a team, we can assume that their RS and RA follow a Weibull distirbution with the above parameters. Then there will be two ways that we can predict how each team will win (namely using the RS or RA for each team).

In [2]:
#Initialize our values of gamma and beta as
#we are fixing them now, but might play with
#this later
gamma = 1.82
beta = 0

In [3]:
##Read data from Joe's csv file as gl_2010 (i.e. game log 2010)
gl_2010 = pd.read_csv("./game_log_sorter/sorted_game_logs/gl2010_sorted.csv")

In [4]:
##We can take a quick look at our data
gl_2010.head()

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311

In [5]:
#Gives the list of teams and alphabetizes it
team_list = gl_2010.team.value_counts().keys()
team_list = sorted(team_list)

We will now make the data that we need, but we shall do this individually for ANA as a test case, and then we will generalize it for all the other teams all at once

In [6]:
#This is a function that takes in a dataframe
#for an individual team, and returns a series
#which gives the cumulative sum of the runs scored
#for all the games prior to that given one
def make_previous_cum_sum_rs(df):
    cumsumlist = [0]
    for x in df.runs_scored.cumsum():
        cumsumlist.append(x)
    cumsumlist.pop()
    return pd.Series(cumsumlist)
#This is an analogous function for runs allowed
def make_previous_cum_sum_ra(df):
    cumsumlist = [0]
    for x in df.runs_allowed.cumsum():
        cumsumlist.append(x)
    cumsumlist.pop()
    return pd.Series(cumsumlist)

In [7]:
#This is a function that takes in the data frame
#it then takes the given cumulative runs scored
#from all previous games, and uses it to construct
#the alpha parameters
def make_alpha_rs(df, beta, gamma):
    return (df.previous_cumulative_runs_scored - beta) / (math.gamma(1 + (1 / gamma)))
#This is the analogous function for runs allowed
def make_alpha_ra(df, beta, gamma):
    return (df.previous_cumulative_runs_allowed - beta) / (math.gamma(1 + (1 / gamma)))

In [8]:
#Creates a dataframe just for the team ANA
ANA_2010 = gl_2010.loc[gl_2010.team == "ANA"]
ANA_2010.head()

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311

In [9]:
#We shall add columns for cumulative RS, RA, 
#and the corresponding Weibull pararmeters
ANA_2010.insert(len(ANA_2010.T),"previous_cumulative_runs_scored", make_previous_cum_sum_rs(ANA_2010))
ANA_2010.insert(len(ANA_2010.T),"previous_cumulative_runs_allowed", make_previous_cum_sum_ra(ANA_2010))
ANA_2010.insert(len(ANA_2010.T),"alpha_rs", make_alpha_rs(ANA_2010, beta, gamma))
ANA_2010.insert(len(ANA_2010.T),"alpha_ra", make_alpha_ra(ANA_2010, beta, gamma))

In [10]:
ANA_2010.head()

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat,previous_cumulative_runs_scored,previous_cumulative_runs_allowed,alpha_rs,alpha_ra
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213,0,0,0.000000,0.000000
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292,6,3,6.750460,3.375230
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054,9,8,10.125690,9.000613
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089,11,12,12.375843,13.500920
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311,12,22,13.500920,24.751687

We will now break everything up in terms of the teams for the general case of the code to break things into each of the teams

In [11]:
#This function takes in our data and the name of the team and 
#returns a dataframe that is just for that specific team
#it then calls a function that adds the additional data we 
#want from what we have
def make_df_for_team(gamelog, team):
    df = gamelog.loc[gamelog.team == team].reset_index(drop = True) 
    #Note we had to reindex otherwise only the first 
    return make_df_from_team_df(df)
    
#This function takes in the dataframe for a specific team
#It then appends new columns with the additional data that we 
#are interested in which we will be using
def make_df_from_team_df(df):
    df.insert(len(df.T),"previous_cumulative_runs_scored", make_previous_cum_sum_rs(df))
    df.insert(len(df.T),"previous_cumulative_runs_allowed", make_previous_cum_sum_ra(df))
    df.insert(len(df.T),"alpha_rs", make_alpha_rs(df, beta, gamma))
    df.insert(len(df.T),"alpha_ra", make_alpha_ra(df, beta, gamma))
    return df

In [12]:
#Make a list for the data frame for each team
frames = []
for team in team_list:
    df = make_df_for_team(gl_2010, team)#for each data frame we get the rest of the data we want
    frames.append(df)  #adds the dataframe for that team to the list
result = pd.concat(frames) #puts together all the dataframes into a single dataframe
result["alpha_rs"] = result["alpha_rs"] + (result["alpha_rs"] == 0) #adds 1 if alpha_rs = 0
result["alpha_ra"] = result["alpha_ra"] + (result["alpha_ra"] == 0) #adds 1 if alpha_ra = 0

In [13]:
result

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat,previous_cumulative_runs_scored,previous_cumulative_runs_allowed,alpha_rs,alpha_ra
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213,0,0,1.000000,1.000000
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292,6,3,6.750460,3.375230
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054,9,8,10.125690,9.000613
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089,11,12,12.375843,13.500920
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311,12,22,13.500920,24.751687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,160,20100928,WAS,PHI,2,1,158,27,3,35,9,1.0,0.430380,0.444856,0.485334,647,724,727.924607,814.555511
158,161,20100929,WAS,PHI,1,7,159,30,3,33,8,0.0,0.427673,0.440874,0.484297,649,725,730.174761,815.680588
159,78,20101001,WAS,NYN,1,2,160,33,3,33,4,0.0,0.425000,0.440287,0.484187,650,732,731.299837,823.556124
160,79,20101002,WAS,NYN,2,7,161,32,6,33,11,0.0,0.422360,0.437123,0.483369,651,734,732.424914,825.806278
161,80,20101003,WAS,NYN,2,1,162,46,6,46,8,1.0,0.425926,0.437964,0.483642,653,741,734.675067,833.681814

Now that we have the data that we are interested in, we can now build up our predictive model, we shall do this by using the alpha_ra and alpha_rs variables as our variables for our Weibull distributions for each team.

We shall now go through things for the first game of the season before writing the code that will do it all at once. Note that this code only works for the first game of the season, but when iterated, we found that it failed at game 4 because CHA's game 4 was against MIN and ANA also was against MIN in game 4, so we have to go about this a separate way.

In [14]:
def run_simulation_same_rs (alpha1_rs, alpha2_rs, rs_1 = 0,rs_2 = 0):
    team1wincount = 0
    for x in range(1001):
        rs1 = (gamma * np.random.weibull(alpha1_rs)) - rs_1
        rs2 = (gamma * np.random.weibull(alpha2_rs)) - rs_2
        if (rs1>rs2):
            team1wincount = team1wincount + 1
    return team1wincount

def run_simulation_same_ra (alpha1_ra, alpha2_ra, ra_1 = 0, ra_2 = 0):
    team1wincount = 0
    for x in range(1001):
        ra1 = (gamma * np.random.weibull(alpha1_ra)) - ra_1
        ra2 = (gamma * np.random.weibull(alpha2_ra)) - ra_2
        if (ra2>ra1):
            team1wincount = team1wincount + 1
    return team1wincount

def run_simulation_rs_ra (alpha1_rs, alpha1_ra, alpha2_rs,alpha2_ra, rs_1 = 0, rs_2 = 0, ra_1 = 0, ra_2 = 0):
    team1wincount = 0
    for x in range(1001):
        rs1 = (gamma * np.random.weibull(alpha1_rs)) - rs_1
        rs2 = (gamma * np.random.weibull(alpha2_rs)) - rs_2
        ra1 = (gamma * np.random.weibull(alpha1_ra)) - ra_1
        ra2 = (gamma * np.random.weibull(alpha2_ra)) - ra_2
        if (rs1-ra2>rs2-ra1):
            team1wincount = team1wincount + 1
    return team1wincount

Here we shall do this instead of breaking it up by the game number, we shall do this for each individual team. Thus, for each team we will look at who is the winner, we shall do this for ANA and then generalize to all the others by iterating over the team_list things might also get difficult to code if there are double headers, but we will cross that bridge when we do

In [15]:
team_games = result.loc[result.team == "ANA"]

In [16]:
result.head()

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat,previous_cumulative_runs_scored,previous_cumulative_runs_allowed,alpha_rs,alpha_ra
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213,0,0,1.000000,1.000000
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292,6,3,6.750460,3.375230
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054,9,8,10.125690,9.000613
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089,11,12,12.375843,13.500920
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311,12,22,13.500920,24.751687

In [17]:
team_games.head()

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,opponent_hits,win_loss,win_frac_actual,win_frac_cummulative_pythagorean,win_frac_cummulative_pythagenpat,previous_cumulative_runs_scored,previous_cumulative_runs_allowed,alpha_rs,alpha_ra
0,81,20100405,ANA,MIN,6,3,1,33,9,32,7,1.0,1.000000,0.800000,0.786213,0,0,1.000000,1.000000
1,82,20100406,ANA,MIN,3,5,2,33,8,32,9,0.0,0.500000,0.558621,0.548292,6,3,6.750460,3.375230
2,83,20100407,ANA,MIN,2,4,3,35,9,34,7,0.0,0.333333,0.456604,0.468054,9,8,10.125690,9.000613
3,84,20100408,ANA,MIN,1,10,4,34,8,37,11,0.0,0.250000,0.229299,0.297089,11,12,12.375843,13.500920
4,85,20100409,ANA,OAK,4,10,5,35,8,41,13,0.0,0.200000,0.200000,0.275311,12,22,13.500920,24.751687

In [18]:
#iterate over all the game numbers
import random
random.seed(10)
team_games.insert(len(team_games.T),"same_rs_percentage",0)
team_games.insert(len(team_games.T),"same_ra_percentage",0)
team_games.insert(len(team_games.T),"both_percentage",0)
for game_number in range(len(team_games)):
    #get the index for where the opponent is for this game
    opponent_index = result.loc[(result.team == team_games.opponent[game_number]) 
                         & (result.opponent == "ANA")
                         & (result.Date == team_games.Date[game_number])
                         & (result.runs_allowed == team_games.runs_scored[game_number])
                        ].values[0][0]
    #gets the alpha values for each team
    home_alpha_rs = team_games.alpha_rs[game_number]
    home_alpha_ra = team_games.alpha_ra[game_number]
    away_alpha_rs = result.reset_index(drop = True).alpha_rs[opponent_index]
    away_alpha_ra = result.reset_index(drop = True).alpha_ra[opponent_index]
    home_rs = team_games.previous_cumulative_runs_scored[game_number]
    home_ra = team_games.previous_cumulative_runs_allowed[game_number]
    away_rs = result.reset_index(drop = True).previous_cumulative_runs_scored[opponent_index]
    away_ra = result.reset_index(drop = True).previous_cumulative_runs_allowed[opponent_index]
    
    team1wincount_same_rs = run_simulation_same_rs(home_alpha_rs,away_alpha_rs)
    team1wincount_same_ra = run_simulation_same_ra(home_alpha_ra,away_alpha_ra)
    team1wincount_different = run_simulation_rs_ra (home_alpha_rs, 
                                                    home_alpha_ra, 
                                                    away_alpha_rs,
                                                    away_alpha_ra)
    #print(team1wincount_same_rs)
    team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
    team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
    team_games["both_percentage"][game_number] = team1wincount_different/1001
team_games.insert(len(team_games.T),"same_rs_prediction",(team_games["same_rs_percentage"].values>.5)*1)
team_games.insert(len(team_games.T),"same_ra_prediction",(team_games["same_ra_percentage"].values>.5)*1)
team_games.insert(len(team_games.T),"both_prediction",(team_games["both_percentage"].values>.5)*1)
team_games.insert(len(team_games.T),"same_rs_prediction_correct",(team_games.same_rs_prediction == team_games.win_loss)*1)
team_games.insert(len(team_games.T),"same_ra_prediction_correct",(team_games.same_ra_prediction == team_games.win_loss)*1)
team_games.insert(len(team_games.T),"both_prediction_correct",(team_games.both_prediction == team_games.win_loss)*1)
print("ANA RS Prediction accuracy " + str((team_games.cumsum().same_rs_prediction_correct[161])/162))
print("ANA RA Prediction accuracy " + str((team_games.cumsum().same_ra_prediction_correct[161])/162))
print("ANA Both Prediction accuracy " + str((team_games.cumsum().both_prediction_correct[161])/162))

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\4045668830.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\4045668830.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\4045668830.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

ANA RS Prediction accuracy 0.5370370370370371
ANA RA Prediction accuracy 0.43209876543209874
ANA Both Prediction accuracy 0.5123456790123457

In [19]:
team_games

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,alpha_ra,same_rs_percentage,same_ra_percentage,both_percentage,same_rs_prediction,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct
0,81,20100405,ANA,MIN,6,3,1,33,9,32,...,1.000000,0.508492,0.508492,0.495504,1,1,0,1,1,0
1,82,20100406,ANA,MIN,3,5,2,33,8,32,...,3.375230,0.491508,0.496503,0.502498,0,0,1,1,1,0
2,83,20100407,ANA,MIN,2,4,3,35,9,34,...,9.000613,0.495504,0.486513,0.500500,0,0,1,1,1,0
3,84,20100408,ANA,MIN,1,10,4,34,8,37,...,13.500920,0.507493,0.511489,0.502498,1,1,1,0,0,0
4,85,20100409,ANA,OAK,4,10,5,35,8,41,...,24.751687,0.624376,0.383616,0.577423,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,161,20100929,ANA,OAK,2,1,158,39,8,40,...,771.802597,0.560440,0.464535,0.569431,1,0,1,1,0,1
158,77,20100930,ANA,TEX,2,3,159,31,5,29,...,772.927674,0.491508,0.512488,0.520480,0,1,1,1,0,0
159,78,20101001,ANA,TEX,5,4,160,41,11,41,...,776.302904,0.456543,0.504496,0.478521,0,1,0,0,1,0
160,79,20101002,ANA,TEX,2,6,161,32,6,32,...,780.803211,0.466533,0.523477,0.501499,0,1,1,1,0,0
161,80,20101003,ANA,TEX,6,2,162,33,6,34,...,787.553671,0.507493,0.482517,0.485514,1,0,0,1,0,0

In [20]:
print("ANA RS Prediction accuracy " + str((team_games.cumsum().same_rs_prediction_correct[161])/162))
print("ANA RA Prediction accuracy " + str((team_games.cumsum().same_ra_prediction_correct[161])/162))
print("ANA Both Prediction accuracy " + str((team_games.cumsum().both_prediction_correct[161])/162))

ANA RS Prediction accuracy 0.5370370370370371
ANA RA Prediction accuracy 0.43209876543209874
ANA Both Prediction accuracy 0.5123456790123457

In [21]:
def simulate_for_team(result, team):
    team_games = result.loc[result.team == team]
    #iterate over all the game numbers
    team_games.insert(len(team_games.T),"same_rs_percentage",0)
    team_games.insert(len(team_games.T),"same_ra_percentage",0)
    team_games.insert(len(team_games.T),"both_percentage",0)
    for game_number in range(len(team_games)):
        #get the index for where the opponent is for this game
        opponent_index = result.loc[(result.team == team_games.opponent[game_number]) 
                             & (result.opponent == team)
                             & (result.Date == team_games.Date[game_number])
                             & (result.runs_allowed == team_games.runs_scored[game_number])
                            ].values[0][0]
        #gets the alpha values for each team
        home_alpha_rs = team_games.alpha_rs[game_number]
        home_alpha_ra = team_games.alpha_ra[game_number]
        away_alpha_rs = result.reset_index(drop = True).alpha_rs[opponent_index]
        away_alpha_ra = result.reset_index(drop = True).alpha_ra[opponent_index]
        home_rs = team_games.previous_cumulative_runs_scored[game_number]
        home_ra = team_games.previous_cumulative_runs_allowed[game_number]
        away_rs = result.reset_index(drop = True).previous_cumulative_runs_scored[opponent_index]
        away_ra = result.reset_index(drop = True).previous_cumulative_runs_allowed[opponent_index]
        team1wincount_same_rs = run_simulation_same_rs(home_alpha_rs,away_alpha_rs)
        team1wincount_same_ra = run_simulation_same_ra(home_alpha_ra,away_alpha_ra)
        team1wincount_different = run_simulation_rs_ra (home_alpha_rs, 
                                                    home_alpha_ra, 
                                                    away_alpha_rs,
                                                    away_alpha_ra)
        #print(team1wincount_same_rs)
        team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
        team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
        team_games["both_percentage"][game_number] = team1wincount_different/1001
    team_games.insert(len(team_games.T),"same_rs_prediction",(team_games["same_rs_percentage"].values>.5)*1)
    team_games.insert(len(team_games.T),"same_ra_prediction",(team_games["same_ra_percentage"].values>.5)*1)
    team_games.insert(len(team_games.T),"both_prediction",(team_games["both_percentage"].values>.5)*1)
    team_games.insert(len(team_games.T),"same_rs_prediction_correct",(team_games.same_rs_prediction == team_games.win_loss)*1)
    team_games.insert(len(team_games.T),"same_ra_prediction_correct",(team_games.same_ra_prediction == team_games.win_loss)*1)
    team_games.insert(len(team_games.T),"both_prediction_correct",(team_games.both_prediction == team_games.win_loss)*1)
    team_games.insert(len(team_games.T),"combine_predictions",((team_games.same_rs_prediction + team_games.same_ra_prediction + team_games.both_prediction) >= 2)*1)
    team_games.insert(len(team_games.T),"combine_predictions_correct",(team_games.combine_predictions == team_games.win_loss)*1)

    print(str(team) + " RS Prediction accuracy " + str((team_games.cumsum().same_rs_prediction_correct[len(team_games) - 1])/len(team_games)))
    print(str(team) + " RA Prediction accuracy " + str((team_games.cumsum().same_ra_prediction_correct[len(team_games) - 1])/len(team_games)))
    print(str(team) + " Both Prediction accuracy " + str((team_games.cumsum().both_prediction_correct[len(team_games) - 1])/len(team_games)))
    print(str(team) + " Combine Prediction accuracy " + str((team_games.cumsum().combine_predictions_correct[len(team_games) - 1])/len(team_games)))
    return team_games

In [22]:
#This will loop through going through each game 
#number of the season
#Make a list for the data frame for each team
frames = []
for team in team_list:
    print(team)
    df = simulate_for_team(result,team) #for each data frame we get the rest of the data we want
    frames.append(df)  #adds the dataframe for that team to the list
final_results = pd.concat(frames)

ANA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

ANA RS Prediction accuracy 0.5432098765432098
ANA RA Prediction accuracy 0.48148148148148145
ANA Both Prediction accuracy 0.5370370370370371
ANA Combine Prediction accuracy 0.5493827160493827
ARI

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

ARI RS Prediction accuracy 0.5555555555555556
ARI RA Prediction accuracy 0.5246913580246914
ARI Both Prediction accuracy 0.5370370370370371
ARI Combine Prediction accuracy 0.5679012345679012
ATL

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

ATL RS Prediction accuracy 0.6049382716049383
ATL RA Prediction accuracy 0.38271604938271603
ATL Both Prediction accuracy 0.6234567901234568
ATL Combine Prediction accuracy 0.6234567901234568
BAL

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

BAL RS Prediction accuracy 0.5555555555555556
BAL RA Prediction accuracy 0.4382716049382716
BAL Both Prediction accuracy 0.5617283950617284
BAL Combine Prediction accuracy 0.5555555555555556
BOS

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

BOS RS Prediction accuracy 0.5370370370370371
BOS RA Prediction accuracy 0.47530864197530864
BOS Both Prediction accuracy 0.5246913580246914
BOS Combine Prediction accuracy 0.5308641975308642
CHA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

CHA RS Prediction accuracy 0.5432098765432098
CHA RA Prediction accuracy 0.5
CHA Both Prediction accuracy 0.5246913580246914
CHA Combine Prediction accuracy 0.5370370370370371
CHN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

CHN RS Prediction accuracy 0.47530864197530864
CHN RA Prediction accuracy 0.47530864197530864
CHN Both Prediction accuracy 0.5185185185185185
CHN Combine Prediction accuracy 0.47530864197530864
CIN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

CIN RS Prediction accuracy 0.5555555555555556
CIN RA Prediction accuracy 0.4876543209876543
CIN Both Prediction accuracy 0.5246913580246914
CIN Combine Prediction accuracy 0.5555555555555556
CLE

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

CLE RS Prediction accuracy 0.5493827160493827
CLE RA Prediction accuracy 0.48148148148148145
CLE Both Prediction accuracy 0.5493827160493827
CLE Combine Prediction accuracy 0.5555555555555556
COL

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

COL RS Prediction accuracy 0.5802469135802469
COL RA Prediction accuracy 0.4074074074074074
COL Both Prediction accuracy 0.6049382716049383
COL Combine Prediction accuracy 0.5802469135802469
DET

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

DET RS Prediction accuracy 0.6049382716049383
DET RA Prediction accuracy 0.3950617283950617
DET Both Prediction accuracy 0.5925925925925926
DET Combine Prediction accuracy 0.5802469135802469
FLO

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

FLO RS Prediction accuracy 0.5432098765432098
FLO RA Prediction accuracy 0.47530864197530864
FLO Both Prediction accuracy 0.5123456790123457
FLO Combine Prediction accuracy 0.5308641975308642
HOU

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

HOU RS Prediction accuracy 0.5864197530864198
HOU RA Prediction accuracy 0.4382716049382716
HOU Both Prediction accuracy 0.5802469135802469
HOU Combine Prediction accuracy 0.5864197530864198
KCA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

KCA RS Prediction accuracy 0.5123456790123457
KCA RA Prediction accuracy 0.4876543209876543
KCA Both Prediction accuracy 0.5061728395061729
KCA Combine Prediction accuracy 0.5
LAN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

LAN RS Prediction accuracy 0.5740740740740741
LAN RA Prediction accuracy 0.46296296296296297
LAN Both Prediction accuracy 0.5555555555555556
LAN Combine Prediction accuracy 0.5802469135802469
MIL

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

MIL RS Prediction accuracy 0.4876543209876543
MIL RA Prediction accuracy 0.48148148148148145
MIL Both Prediction accuracy 0.5
MIL Combine Prediction accuracy 0.5
MIN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

MIN RS Prediction accuracy 0.5802469135802469
MIN RA Prediction accuracy 0.4506172839506173
MIN Both Prediction accuracy 0.5802469135802469
MIN Combine Prediction accuracy 0.5740740740740741
NYA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

NYA RS Prediction accuracy 0.5370370370370371
NYA RA Prediction accuracy 0.47530864197530864
NYA Both Prediction accuracy 0.5061728395061729
NYA Combine Prediction accuracy 0.5308641975308642
NYN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

NYN RS Prediction accuracy 0.5740740740740741
NYN RA Prediction accuracy 0.43209876543209874
NYN Both Prediction accuracy 0.5987654320987654
NYN Combine Prediction accuracy 0.5802469135802469
OAK

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

OAK RS Prediction accuracy 0.5679012345679012
OAK RA Prediction accuracy 0.4691358024691358
OAK Both Prediction accuracy 0.5617283950617284
OAK Combine Prediction accuracy 0.5740740740740741
PHI

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

PHI RS Prediction accuracy 0.5802469135802469
PHI RA Prediction accuracy 0.42592592592592593
PHI Both Prediction accuracy 0.5493827160493827
PHI Combine Prediction accuracy 0.5802469135802469
PIT

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

PIT RS Prediction accuracy 0.6172839506172839
PIT RA Prediction accuracy 0.48148148148148145
PIT Both Prediction accuracy 0.6111111111111112
PIT Combine Prediction accuracy 0.6234567901234568
SDN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

SDN RS Prediction accuracy 0.5
SDN RA Prediction accuracy 0.4876543209876543
SDN Both Prediction accuracy 0.5
SDN Combine Prediction accuracy 0.5061728395061729
SEA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

SEA RS Prediction accuracy 0.5493827160493827
SEA RA Prediction accuracy 0.4691358024691358
SEA Both Prediction accuracy 0.5493827160493827
SEA Combine Prediction accuracy 0.5432098765432098
SFN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

SFN RS Prediction accuracy 0.5802469135802469
SFN RA Prediction accuracy 0.47530864197530864
SFN Both Prediction accuracy 0.5370370370370371
SFN Combine Prediction accuracy 0.5740740740740741
SLN

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

SLN RS Prediction accuracy 0.6049382716049383
SLN RA Prediction accuracy 0.43209876543209874
SLN Both Prediction accuracy 0.6234567901234568
SLN Combine Prediction accuracy 0.6049382716049383
TBA

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

TBA RS Prediction accuracy 0.5370370370370371
TBA RA Prediction accuracy 0.46296296296296297
TBA Both Prediction accuracy 0.5246913580246914
TBA Combine Prediction accuracy 0.5370370370370371
TEX

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

TEX RS Prediction accuracy 0.5555555555555556
TEX RA Prediction accuracy 0.4567901234567901
TEX Both Prediction accuracy 0.5864197530864198
TEX Combine Prediction accuracy 0.5740740740740741
TOR

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

TOR RS Prediction accuracy 0.5308641975308642
TOR RA Prediction accuracy 0.4382716049382716
TOR Both Prediction accuracy 0.5617283950617284
TOR Combine Prediction accuracy 0.5493827160493827
WAS

C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_rs_percentage"][game_number] = team1wincount_same_rs/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["same_ra_percentage"][game_number] = team1wincount_same_ra/1001
C:\Users\steve\AppData\Local\Temp\ipykernel_4736\1835314475.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games["both_percentage"][game_number] = team1wincount_different/1001

WAS RS Prediction accuracy 0.5432098765432098
WAS RA Prediction accuracy 0.42592592592592593
WAS Both Prediction accuracy 0.5802469135802469
WAS Combine Prediction accuracy 0.5555555555555556

In [23]:
final_results

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,same_ra_percentage,both_percentage,same_rs_prediction,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct,combine_predictions,combine_predictions_correct
0,81,20100405,ANA,MIN,6,3,1,33,9,32,...,0.478521,0.493506,0,0,0,0,0,0,0,0
1,82,20100406,ANA,MIN,3,5,2,33,8,32,...,0.494505,0.506494,0,0,1,1,1,0,0,1
2,83,20100407,ANA,MIN,2,4,3,35,9,34,...,0.498501,0.490509,0,0,0,1,1,1,0,1
3,84,20100408,ANA,MIN,1,10,4,34,8,37,...,0.503497,0.501499,0,1,1,1,0,0,1,0
4,85,20100409,ANA,OAK,4,10,5,35,8,41,...,0.355644,0.603397,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,160,20100928,WAS,PHI,2,1,158,27,3,35,...,0.448551,0.585415,1,0,1,1,0,1,1,1
158,161,20100929,WAS,PHI,1,7,159,30,3,33,...,0.470529,0.606394,1,0,1,0,1,0,1,0
159,78,20101001,WAS,NYN,1,2,160,33,3,33,...,0.474525,0.504496,1,0,1,0,1,0,1,0
160,79,20101002,WAS,NYN,2,7,161,32,6,33,...,0.509491,0.471528,1,1,0,0,0,1,1,0
161,80,20101003,WAS,NYN,2,1,162,46,6,46,...,0.485514,0.495504,0,0,0,0,0,0,0,0

In [24]:
final_results.reset_index(drop = True).cumsum().both_prediction_correct[4859]/4860

0.5541152263374486

In [25]:
print("RS Prediction accuracy " + str((final_results.reset_index(drop = True).cumsum().same_rs_prediction_correct[4859])/4860))
print("RA Prediction accuracy " + str((final_results.reset_index(drop = True).cumsum().same_ra_prediction_correct[4859])/4860))
print("Both Prediction accuracy " + str((final_results.reset_index(drop = True).cumsum().both_prediction_correct[4859])/4860))
print("Combine Prediction accuracy " + str((final_results.reset_index(drop = True).cumsum().combine_predictions_correct[4859])/4860))

RS Prediction accuracy 0.5555555555555556
RA Prediction accuracy 0.45925925925925926
Both Prediction accuracy 0.5541152263374486
Combine Prediction accuracy 0.557201646090535

Note: for the entire season it seems as though this model is only marginally better than flipping a coin, but at the beginning of the season we pretty much were just flipping a coin, so we might think about if we just take all the games of the season starting after game 50 (we can change this) since this metric is used part way through the season

In [26]:
LaterSeasondf = final_results.loc[final_results.game_number >=75]

In [27]:
LaterSeasondf

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,same_ra_percentage,both_percentage,same_rs_prediction,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct,combine_predictions,combine_predictions_correct
74,115,20100624,ANA,LAN,6,10,75,35,12,41,...,0.463536,0.626374,1,0,1,0,1,0,1,0
75,116,20100625,ANA,COL,3,4,76,38,8,43,...,0.468531,0.608392,1,0,1,0,1,0,1,0
76,117,20100626,ANA,COL,4,2,77,28,4,30,...,0.458541,0.633367,1,0,1,1,0,1,1,1
77,118,20100627,ANA,COL,10,3,78,33,9,35,...,0.458541,0.579421,1,0,1,1,0,1,1,1
78,119,20100629,ANA,TEX,6,5,79,34,11,37,...,0.432567,0.582418,1,0,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,160,20100928,WAS,PHI,2,1,158,27,3,35,...,0.448551,0.585415,1,0,1,1,0,1,1,1
158,161,20100929,WAS,PHI,1,7,159,30,3,33,...,0.470529,0.606394,1,0,1,0,1,0,1,0
159,78,20101001,WAS,NYN,1,2,160,33,3,33,...,0.474525,0.504496,1,0,1,0,1,0,1,0
160,79,20101002,WAS,NYN,2,7,161,32,6,33,...,0.509491,0.471528,1,1,0,0,0,1,1,0
161,80,20101003,WAS,NYN,2,1,162,46,6,46,...,0.485514,0.495504,0,0,0,0,0,0,0,0

In [28]:
for number in range(75,100):
    LaterSeasondf = final_results.loc[final_results.game_number >=number]
    print("Prediction after game number " + str(number))
    print("RS Prediction accuracy " + str((LaterSeasondf.reset_index().cumsum().same_rs_prediction_correct[len(LaterSeasondf)-1])/len(LaterSeasondf)))
    print("RA Prediction accuracy " + str((LaterSeasondf.reset_index().cumsum().same_ra_prediction_correct[len(LaterSeasondf)-1])/len(LaterSeasondf)))
    print("Both Prediction accuracy " + str((LaterSeasondf.reset_index().cumsum().both_prediction_correct[len(LaterSeasondf)-1])/len(LaterSeasondf)))
    print("Both Combine accuracy " + str((LaterSeasondf.reset_index().cumsum().Combine_Predictions_correct[len(LaterSeasondf)-1])/len(LaterSeasondf)))

Prediction after game number 75
RS Prediction accuracy 0.5450757575757575
RA Prediction accuracy 0.4693181818181818
Both Prediction accuracy 0.5428030303030303

AttributeError: 'DataFrame' object has no attribute 'Combine_Predictions_correct'

For the entirety of the season, we see that our "BOTH" prediction is about 55% accuracte, but we see for each of the individual teams some of the "BOTH" predictions are about 60% while others are closer to 50%, so perhaps there is some feature where this actually becomes an actually decent model. Thus, we might see how the prediction goes for each team and how their actual win percentage is different from our simulated one.

In [29]:
for team in team_list:
    df = final_results.loc[final_results.team == team]
    print(team)
    print("Wins: " + str(df.reset_index().cumsum().win_loss[len(df)-1]))
    print("Win Percentage: " + str(df.reset_index().cumsum().win_loss[len(df)-1]/len(df)))
    print("Predicted Win Percentage:" + str(df.reset_index().cumsum().both_prediction[len(df)-1]/len(df)))
    print("Accuracy of Predictions:" + str(df.reset_index().cumsum().both_prediction_correct[len(df)-1]/len(df)))
    print("Combine Accuracy of Predictions:" + str(df.reset_index().cumsum().both_prediction_correct[len(df)-1]/len(df)))
    print()

ANA
Wins: 80.0
Win Percentage: 0.49382716049382713
Predicted Win Percentage:0.5370370370370371
Accuracy of Predictions:0.5370370370370371
Combine Accuracy of Predictions:0.5370370370370371

ARI
Wins: 65.0
Win Percentage: 0.4012345679012346
Predicted Win Percentage:0.6172839506172839
Accuracy of Predictions:0.5370370370370371
Combine Accuracy of Predictions:0.5370370370370371

ATL
Wins: 91.0
Win Percentage: 0.5617283950617284
Predicted Win Percentage:0.5308641975308642
Accuracy of Predictions:0.6234567901234568
Combine Accuracy of Predictions:0.6234567901234568

BAL
Wins: 66.0
Win Percentage: 0.4074074074074074
Predicted Win Percentage:0.5370370370370371
Accuracy of Predictions:0.5617283950617284
Combine Accuracy of Predictions:0.5617283950617284

BOS
Wins: 89.0
Win Percentage: 0.5493827160493827
Predicted Win Percentage:0.5802469135802469
Accuracy of Predictions:0.5246913580246914
Combine Accuracy of Predictions:0.5246913580246914

CHA
Wins: 88.0
Win Percentage: 0.5432098765432098
Predicted Win Percentage:0.5123456790123457
Accuracy of Predictions:0.5246913580246914
Combine Accuracy of Predictions:0.5246913580246914

CHN
Wins: 75.0
Win Percentage: 0.46296296296296297
Predicted Win Percentage:0.5740740740740741
Accuracy of Predictions:0.5185185185185185
Combine Accuracy of Predictions:0.5185185185185185

CIN
Wins: 91.0
Win Percentage: 0.5617283950617284
Predicted Win Percentage:0.5555555555555556
Accuracy of Predictions:0.5246913580246914
Combine Accuracy of Predictions:0.5246913580246914

CLE
Wins: 69.0
Win Percentage: 0.42592592592592593
Predicted Win Percentage:0.5555555555555556
Accuracy of Predictions:0.5493827160493827
Combine Accuracy of Predictions:0.5493827160493827

COL
Wins: 83.0
Win Percentage: 0.5123456790123457
Predicted Win Percentage:0.5493827160493827
Accuracy of Predictions:0.6049382716049383
Combine Accuracy of Predictions:0.6049382716049383

DET
Wins: 81.0
Win Percentage: 0.5
Predicted Win Percentage:0.5617283950617284
Accuracy of Predictions:0.5925925925925926
Combine Accuracy of Predictions:0.5925925925925926

FLO
Wins: 80.0
Win Percentage: 0.49382716049382713
Predicted Win Percentage:0.5246913580246914
Accuracy of Predictions:0.5123456790123457
Combine Accuracy of Predictions:0.5123456790123457

HOU
Wins: 76.0
Win Percentage: 0.4691358024691358
Predicted Win Percentage:0.49382716049382713
Accuracy of Predictions:0.5802469135802469
Combine Accuracy of Predictions:0.5802469135802469

KCA
Wins: 67.0
Win Percentage: 0.41358024691358025
Predicted Win Percentage:0.5740740740740741
Accuracy of Predictions:0.5061728395061729
Combine Accuracy of Predictions:0.5061728395061729

LAN
Wins: 80.0
Win Percentage: 0.49382716049382713
Predicted Win Percentage:0.5555555555555556
Accuracy of Predictions:0.5555555555555556
Combine Accuracy of Predictions:0.5555555555555556

MIL
Wins: 77.0
Win Percentage: 0.47530864197530864
Predicted Win Percentage:0.5925925925925926
Accuracy of Predictions:0.5
Combine Accuracy of Predictions:0.5

MIN
Wins: 94.0
Win Percentage: 0.5802469135802469
Predicted Win Percentage:0.5308641975308642
Accuracy of Predictions:0.5802469135802469
Combine Accuracy of Predictions:0.5802469135802469

NYA
Wins: 95.0
Win Percentage: 0.5864197530864198
Predicted Win Percentage:0.5740740740740741
Accuracy of Predictions:0.5061728395061729
Combine Accuracy of Predictions:0.5061728395061729

NYN
Wins: 79.0
Win Percentage: 0.4876543209876543
Predicted Win Percentage:0.5185185185185185
Accuracy of Predictions:0.5987654320987654
Combine Accuracy of Predictions:0.5987654320987654

OAK
Wins: 81.0
Win Percentage: 0.5
Predicted Win Percentage:0.49382716049382713
Accuracy of Predictions:0.5617283950617284
Combine Accuracy of Predictions:0.5617283950617284

PHI
Wins: 97.0
Win Percentage: 0.5987654320987654
Predicted Win Percentage:0.5555555555555556
Accuracy of Predictions:0.5493827160493827
Combine Accuracy of Predictions:0.5493827160493827

PIT
Wins: 57.0
Win Percentage: 0.35185185185185186
Predicted Win Percentage:0.5432098765432098
Accuracy of Predictions:0.6111111111111112
Combine Accuracy of Predictions:0.6111111111111112

SDN
Wins: 90.0
Win Percentage: 0.5555555555555556
Predicted Win Percentage:0.5
Accuracy of Predictions:0.5
Combine Accuracy of Predictions:0.5

SEA
Wins: 61.0
Win Percentage: 0.3765432098765432
Predicted Win Percentage:0.5061728395061729
Accuracy of Predictions:0.5493827160493827
Combine Accuracy of Predictions:0.5493827160493827

SFN
Wins: 92.0
Win Percentage: 0.5679012345679012
Predicted Win Percentage:0.5
Accuracy of Predictions:0.5370370370370371
Combine Accuracy of Predictions:0.5370370370370371

SLN
Wins: 86.0
Win Percentage: 0.5308641975308642
Predicted Win Percentage:0.5123456790123457
Accuracy of Predictions:0.6234567901234568
Combine Accuracy of Predictions:0.6234567901234568

TBA
Wins: 96.0
Win Percentage: 0.5925925925925926
Predicted Win Percentage:0.5246913580246914
Accuracy of Predictions:0.5246913580246914
Combine Accuracy of Predictions:0.5246913580246914

TEX
Wins: 90.0
Win Percentage: 0.5555555555555556
Predicted Win Percentage:0.5246913580246914
Accuracy of Predictions:0.5864197530864198
Combine Accuracy of Predictions:0.5864197530864198

TOR
Wins: 85.0
Win Percentage: 0.5246913580246914
Predicted Win Percentage:0.5308641975308642
Accuracy of Predictions:0.5617283950617284
Combine Accuracy of Predictions:0.5617283950617284

WAS
Wins: 69.0
Win Percentage: 0.42592592592592593
Predicted Win Percentage:0.4876543209876543
Accuracy of Predictions:0.5802469135802469
Combine Accuracy of Predictions:0.5802469135802469

Note: After looking at the above it seems as though somehow in our model most teams are predicted to have a win percentage above 50% which doesn't necessarily make sense. This might be due to some how each game is simulated twice, so perhaps we should have a confidence if we make the prediction that they both win that doesn't tell us anything. But if they both agree, then we are confident that the prediction is likely correct.

In [30]:
final_results.loc[final_results.Date == 20100705]

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,same_ra_percentage,both_percentage,same_rs_prediction,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct,combine_predictions,combine_predictions_correct
84,40,20100705,ANA,CHA,2,9,85,31,6,32,...,0.525475,0.449550,0,1,0,1,0,1,0,1
82,120,20100705,ARI,CHN,4,9,83,29,6,35,...,0.466533,0.574426,1,0,1,0,1,0,1,0
82,42,20100705,ATL,PHI,1,3,83,30,5,33,...,0.509491,0.435564,0,1,0,1,0,1,0,1
81,40,20100705,BAL,DET,9,12,82,41,14,42,...,0.527473,0.417582,0,1,0,1,0,1,0,1
82,36,20100705,BOS,TBA,5,6,83,36,10,32,...,0.555445,0.455544,0,1,0,1,0,1,0,1
80,120,20100705,CHA,ANA,9,2,81,32,9,31,...,0.441558,0.568432,1,0,1,1,0,1,1,1
82,39,20100705,CHN,ARI,9,4,83,35,11,29,...,0.525475,0.448551,0,1,0,0,1,0,0,0
83,37,20100705,CIN,NYN,8,6,84,36,11,36,...,0.538462,0.427572,1,1,0,1,1,0,1,1
81,42,20100705,CLE,TEX,9,3,82,37,12,38,...,0.516484,0.432567,0,1,0,0,1,0,0,0
80,120,20100705,DET,BAL,12,9,81,42,17,41,...,0.484515,0.575425,1,0,1,1,0,1,1,1
81,37,20100705,FLO,LAN,6,5,82,35,10,34,...,0.531469,0.443556,0,1,0,0,1,0,0,0
82,43,20100705,KCA,SEA,6,4,83,38,14,38,...,0.525475,0.437562,0,1,0,0,1,0,0,0
81,120,20100705,LAN,FLO,5,6,82,34,8,35,...,0.464535,0.599401,1,0,1,0,1,0,1,0
82,120,20100705,MIL,SFN,1,6,83,33,7,37,...,0.472527,0.605395,1,0,1,0,1,0,1,0
81,40,20100705,NYA,OAK,3,1,82,35,8,29,...,0.531469,0.460539,0,1,0,0,1,0,0,0
82,121,20100705,NYN,CIN,6,8,83,36,9,36,...,0.492507,0.569431,1,0,1,0,1,0,1,0
83,121,20100705,OAK,NYA,1,3,84,29,3,35,...,0.452547,0.558442,1,0,1,0,1,0,1,0
80,116,20100705,PHI,ATL,3,1,81,33,9,30,...,0.477522,0.595405,1,0,1,1,0,1,1,1
81,119,20100705,SEA,KCA,4,6,82,38,8,38,...,0.455544,0.577423,1,0,1,0,1,0,1,0
81,39,20100705,SFN,MIL,6,1,82,37,10,33,...,0.559441,0.419580,0,1,0,0,1,0,0,0
81,120,20100705,TBA,BOS,6,5,82,32,10,36,...,0.418581,0.624376,1,0,1,1,0,1,1,1
81,124,20100705,TEX,CLE,3,9,82,38,11,37,...,0.463536,0.581419,1,0,1,0,1,0,1,0

In [31]:
final_results.insert(len(final_results.T),"Combine_Predictions", final_results.same_rs_prediction + final_results.same_ra_prediction + final_results.both_prediction)

In [32]:
final_results.insert(len(final_results.T),"Combine_Predictions_More", (final_results.Combine_Predictions>= 2) * 1)

In [33]:
final_results.insert(len(final_results.T),"Combine_Predictions_correct", (final_results.Combine_Predictions_More==final_results.win_loss) * 1)

In [34]:
final_results

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct,combine_predictions,combine_predictions_correct,Combine_Predictions,Combine_Predictions_More,Combine_Predictions_correct
0,81,20100405,ANA,MIN,6,3,1,33,9,32,...,0,0,0,0,0,0,0,0,0,0
1,82,20100406,ANA,MIN,3,5,2,33,8,32,...,0,1,1,1,0,0,1,1,0,1
2,83,20100407,ANA,MIN,2,4,3,35,9,34,...,0,0,1,1,1,0,1,0,0,1
3,84,20100408,ANA,MIN,1,10,4,34,8,37,...,1,1,1,0,0,1,0,2,1,0
4,85,20100409,ANA,OAK,4,10,5,35,8,41,...,0,1,0,1,0,1,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,160,20100928,WAS,PHI,2,1,158,27,3,35,...,0,1,1,0,1,1,1,2,1,1
158,161,20100929,WAS,PHI,1,7,159,30,3,33,...,0,1,0,1,0,1,0,2,1,0
159,78,20101001,WAS,NYN,1,2,160,33,3,33,...,0,1,0,1,0,1,0,2,1,0
160,79,20101002,WAS,NYN,2,7,161,32,6,33,...,1,0,0,0,1,1,0,2,1,0
161,80,20101003,WAS,NYN,2,1,162,46,6,46,...,0,0,0,0,0,0,0,0,0,0

In [35]:
print("RA Prediction accuracy " + str((final_results.reset_index(drop = True).cumsum().Combine_Predictions_correct
[4859])/4860))

RA Prediction accuracy 0.557201646090535

In [36]:
df = final_results.loc[(final_results.both_percentage >=.55) | (final_results.both_percentage <=.45)]

In [37]:
df

,index,Date,team,opponent,runs_scored,runs_allowed,game_number,at_bats,hits,opponent_at_bats,...,same_ra_prediction,both_prediction,same_rs_prediction_correct,same_ra_prediction_correct,both_prediction_correct,combine_predictions,combine_predictions_correct,Combine_Predictions,Combine_Predictions_More,Combine_Predictions_correct
4,85,20100409,ANA,OAK,4,10,5,35,8,41,...,0,1,0,1,0,1,0,2,1,0
5,86,20100410,ANA,OAK,4,3,6,36,13,33,...,0,1,1,0,1,1,1,2,1,1
6,87,20100411,ANA,OAK,4,9,7,32,7,34,...,0,1,0,1,0,1,0,2,1,0
7,0,20100413,ANA,NYA,5,7,8,37,11,34,...,1,0,1,0,1,0,1,1,0,1
8,1,20100414,ANA,NYA,5,3,9,36,10,34,...,1,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,157,20100925,WAS,ATL,0,5,155,34,6,33,...,0,1,0,1,0,1,0,2,1,0
155,158,20100926,WAS,ATL,4,2,156,29,7,33,...,0,1,1,0,1,1,1,2,1,1
156,159,20100927,WAS,PHI,0,8,157,28,2,37,...,0,1,0,1,0,1,0,2,1,0
157,160,20100928,WAS,PHI,2,1,158,27,3,35,...,0,1,1,0,1,1,1,2,1,1
158,161,20100929,WAS,PHI,1,7,159,30,3,33,...,0,1,0,1,0,1,0,2,1,0

In [38]:
df.reset_index(drop = True).cumsum().combine_predictions_correct[len(df)-1]/len(df)

0.5609144131586283

In [39]:
points = []
for x in range(100):
    df = final_results.loc[(final_results.both_percentage >=.5 +(.001 * x)) | (final_results.both_percentage <=.5 - (.001 * x))]
    points.append([x * .001,df.reset_index(drop = True).cumsum().combine_predictions_correct[len(df)-1]/len(df)])

In [40]:
points

[[0.0, 0.557201646090535],
 [0.001, 0.5575569358178054],
 [0.002, 0.5569224353628023],
 [0.003, 0.5569991617770327],
 [0.004, 0.5567726985464504],
 [0.005, 0.5576066199872692],
 [0.006, 0.5579509071504802],
 [0.007, 0.5579896907216495],
 [0.008, 0.558632626568585],
 [0.009000000000000001, 0.5587979094076655],
 [0.01, 0.5593777388255916],
 [0.011, 0.5598855129898723],
 [0.012, 0.5593708462560921],
 [0.013000000000000001, 0.5598214285714286],
 [0.014, 0.5601706331387517],
 [0.015, 0.561003163126977],
 [0.016, 0.5616905248807089],
 [0.017, 0.5610591189226204],
 [0.018000000000000002, 0.5606790548290892],
 [0.019, 0.5609137055837563],
 [0.02, 0.5607715547292587],
 [0.021, 0.5605140186915888],
 [0.022, 0.5608951707891637],
 [0.023, 0.5607210626185958],
 [0.024, 0.5589780324737345],
 [0.025, 0.5588094095055209],
 [0.026000000000000002, 0.5587171449240415],
 [0.027, 0.5581395348837209],
 [0.028, 0.5593179049939099],
 [0.029, 0.5601273573352927],
 [0.03, 0.5598617625277709],
 [0.031, 0.5601391650099403],
 [0.032, 0.5595505617977528],
 [0.033, 0.5600502512562814],
 [0.034, 0.5606060606060606],
 [0.035, 0.5607713778228876],
 [0.036000000000000004, 0.5607953097119551],
 [0.037, 0.561556181213207],
 [0.038, 0.5619855967078189],
 [0.039, 0.5620134924753503],
 [0.04, 0.5620437956204379],
 [0.041, 0.561909758656873],
 [0.042, 0.5615100316789863],
 [0.043000000000000003, 0.561552778516352],
 [0.044, 0.5613472333600642],
 [0.045, 0.5613562970936491],
 [0.046, 0.5611608353675075],
 [0.047, 0.5606763021543496],
 [0.048, 0.5606268902941985],
 [0.049, 0.5603543743078627],
 [0.05, 0.5609144131586283],
 [0.051000000000000004, 0.5612359550561797],
 [0.052000000000000005, 0.5611205432937182],
 [0.053, 0.560731637610746],
 [0.054, 0.5617782909930716],
 [0.055, 0.5633556655986018],
 [0.056, 0.5641703377386197],
 [0.057, 0.5645352279455299],
 [0.058, 0.5655688622754491],
 [0.059000000000000004, 0.5652042360060514],
 [0.06, 0.566758325695081],
 [0.061, 0.5651501083255958],
 [0.062, 0.5659667815731746],
 [0.063, 0.5647766867279063],
 [0.064, 0.5634436235142949],
 [0.065, 0.5633528265107213],
 [0.066, 0.5640686922060766],
 [0.067, 0.5623110513940208],
 [0.068, 0.5644004099760848],
 [0.069, 0.5640402637972926],
 [0.07, 0.5628952916373858],
 [0.07100000000000001, 0.562432915921288],
 [0.07200000000000001, 0.5653761869978087],
 [0.073, 0.56377835626627],
 [0.074, 0.5640347563279184],
 [0.075, 0.5661993769470405],
 [0.076, 0.5685258964143426],
 [0.077, 0.5673037820252135],
 [0.078, 0.5654166666666667],
 [0.079, 0.5661670235546039],
 [0.08, 0.5643044619422573],
 [0.081, 0.5653345307588684],
 [0.082, 0.566543438077634],
 [0.083, 0.5627376425855514],
 [0.084, 0.5643031784841076],
 [0.085, 0.564321608040201],
 [0.08600000000000001, 0.5639564992232005],
 [0.08700000000000001, 0.5632978723404255],
 [0.088, 0.5598901098901099],
 [0.089, 0.5590729225551159],
 [0.09, 0.557367501456028],
 [0.091, 0.5550210463018641],
 [0.092, 0.5563816604708798],
 [0.093, 0.5573248407643312],
 [0.094, 0.5570117955439057],
 [0.095, 0.5613079019073569],
 [0.096, 0.5575842696629213],
 [0.097, 0.5567685589519651],
 [0.098, 0.5587349397590361],
 [0.099, 0.5573770491803278]]